services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - app-network
    cgroup: host
    environment:
      - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap

  crawler:
    build: 
      context: ./FastAPIProject1
      dockerfile: Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CRAWL_INTERVAL=3600
    networks:
      - app-network
    depends_on:
      - kafka
  frontend:
    build:
      context: ./untitled
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./untitled:/app
    # environment:
    #   NODE_ENV: production
    command: ["npm", "start"]
    networks:
      - app-network
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network
  kafka:
    image: bitnami/kafka:3.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: no
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: yes
    networks:
      - app-network
  auth-service:
    build:
      context: ./emailService-Auth_Service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/authService
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kmj388
    networks:
      - app-network
    depends_on:
      - mysql
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8003:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - GRADLE_OPTS=-Dorg.gradle.jvmargs="-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError"
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
  subscription:
    build:
      context: ./subscription
      dockerfile: Dockerfile
      args:
        - GRADLE_OPTS=-Dorg.gradle.jvmargs="-Xmx1024m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError"
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/subscription
      - SPRING_DATASOURCE_USERNAME=kmj388
      - SPRING_DATASOURCE_PASSWORD=kmj388
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - postgresql
      - kafka
      - eureka-server
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
  apigateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-network
  postgresql:
    image: bitnami/postgresql:15
    container_name: postgres_container
    environment:
      POSTGRESQL_USERNAME: kmj388
      POSTGRESQL_PASSWORD: kmj388
      POSTGRESQL_DATABASE: subscription
    volumes:
      - ./pgdata:/bitnami/postgresql
    ports:
      - "5432:5432"
    networks:
      - app-network
  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    container_name: email-service
    command: sh -c "python manage.py migrate --noinput && gunicorn email_service.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8084:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=email_service.settings
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kmj388
      MYSQL_DATABASE: authService
    tmpfs:
      - /var/lib/mysql
      - /var/run/mysqld
    command: --secure-file-priv=""
    networks:
      - app-network
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

    networks:
      - app-network
  kafka-consumer:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    command: python manage.py start_kafka_consumer
    depends_on:
      - kafka
      - email-service
    networks:
      - app-network
  celery:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    command: celery -A email_service worker --loglevel=info -Q email_verification_queue
    depends_on:
      - rabbitmq
    networks:
      - app-network
networks:
  app-network:
    driver: bridge